
import { CropType, CropStage, SignalLevel, DecisionRule } from './types';

export const CROP_LIST = Object.values(CropType);
export const STAGE_LIST = Object.values(CropStage);

export const OBSERVED_ISSUES = [
  'Yellowing leaves',
  'Pest activity visible',
  'Stunted growth',
  'Wilting',
  'Holes in leaves'
];

export const CROP_DURATIONS: Record<CropType, Record<CropStage, number>> = {
  [CropType.RICE]: { [CropStage.SOWING]: 25, [CropStage.GROWTH]: 50, [CropStage.FLOWERING]: 30, [CropStage.HARVEST]: 20 },
  [CropType.WHEAT]: { [CropStage.SOWING]: 20, [CropStage.GROWTH]: 60, [CropStage.FLOWERING]: 35, [CropStage.HARVEST]: 25 },
  [CropType.COTTON]: { [CropStage.SOWING]: 30, [CropStage.GROWTH]: 70, [CropStage.FLOWERING]: 40, [CropStage.HARVEST]: 30 },
  [CropType.MAIZE]: { [CropStage.SOWING]: 15, [CropStage.GROWTH]: 45, [CropStage.FLOWERING]: 30, [CropStage.HARVEST]: 25 },
  [CropType.MUSTARD]: { [CropStage.SOWING]: 15, [CropStage.GROWTH]: 50, [CropStage.FLOWERING]: 30, [CropStage.HARVEST]: 20 },
};

export type Language = 'en' | 'hi' | 'te';

export const DICTIONARY = {
  en: {
    APP_NAME: 'Samarth Kisan',
    SUBTITLE: 'Smarter Crop Decisions',
    CROP_SETUP: 'Home',
    SIGNAL: 'Signal',
    PAST_ALERTS: 'History',
    WEATHER_WATCH_TAB: 'Weather',
    TRACKER_TAB: 'Records',
    NOTIFICATIONS_TAB: 'Alerts',
    RISK_MONITOR_TAB: 'Risks',
    LOGBOOK_TAB: 'Logbook',
    SIMULATOR_TAB: 'Simulate',
    AI_CHAT_TAB: 'Sahayak',
    AGRONOMIST_SCAN: 'Agronomist Scan',
    SELECT_CROP: '1. Select Your Crop',
    SELECT_SEASON: '2. Select Season',
    SOWING_DATE: '3. Sowing Date',
    SELECT_STAGE: '4. Current Growth Stage',
    LOCATION: '5. District / Location',
    ISSUES: '6. Any Field Issues?',
    CHECK_STATUS: 'CHECK CROP STATUS',
    LIVE_STATUS: 'Live Status',
    UPDATE_DATA: 'Update Data',
    SAFE_TITLE: 'All Good',
    WARNING_TITLE: 'Attention Needed',
    ALERT_TITLE: 'Critical Action',
    WHAT_IF_TITLE: 'What if I ignore this?',
    RECOMMENDED_ACTION: 'Recommended Action',
    WHY_THIS_ALERT: 'Why this alert?',
    WHY_EXPLANATION_TITLE: 'Detailed Explanation',
    AFFECTED_STAGE_LABEL: 'Affected Stage',
    MATTERS_BECAUSE_LABEL: 'Why it matters now',
    URGENCY: 'Urgency',
    WEATHER: 'Weather Watch',
    WEATHER_FORECAST: '5-Day Forecast',
    HISTORY_TITLE: 'Alert History',
    TRACKER_TITLE: 'Farm Activity Log',
    NOTIFICATIONS_TITLE: 'Recent Notifications',
    TRACKER_PENDING: 'Pending Tasks',
    TRACKER_LOGBOOK: 'Activity History',
    LOGBOOK_TITLE: 'Farm Logbook',
    LOGBOOK_DESC: 'Your farm activity diary',
    SIMULATOR_TITLE: 'Scenario Simulator',
    SIMULATOR_DESC: 'See how alerts change with weather',
    AI_CHAT_TITLE: 'Kisan Sahayak AI',
    AI_CHAT_DESC: 'Ask anything about your crop',
    SCAN_TITLE: 'Digital Agronomist',
    SCAN_DESC: 'Scan your crop, pest, or leaf for a lab diagnosis.',
    START_SCAN: 'START NEW SCAN',
    SCANNING: 'Processing lab analysis...',
    SCAN_RESULT_TITLE: 'Agronomist Lab Report',
    DIAGNOSIS: 'Diagnosis',
    ACTION_PLAN: 'Action Plan',
    PREVENTION: 'Prevention',
    LISTEN_BTN: 'Listen to Advice',
    STOP_LISTEN: 'Stop',
    CLEAR: 'Clear',
    NO_HISTORY: 'No records found.',
    ACTION_TAKEN: 'Action Taken',
    ACTION_NOT_TAKEN: 'Not Taken',
    OFFLINE_BANNER: 'Offline mode – showing last available guidance.',
    CONFIDENCE: 'Confidence',
    LOW_COST: 'Low Cost Remedy',
    FEEDBACK_BTN: 'Mark as Done',
    FEEDBACK_DONE: 'Action Recorded ✓',
    STAGE_SUGGESTION: 'Estimated stage:',
    NEXT_STAGE: 'Next Stage',
    DAYS_REMAINING: 'days left',
    CROP_TIMELINE: 'Crop Progress',
    IGNORE_RISK_HOURS: 'Action needed within {h} hours',
    IGNORE_RISK_DAYS: 'Action needed within {d} days',
    MARKET_ACCESS: 'Market Connect',
    MARKET_PRICE: 'Mandi Price',
    BUY_SELL: 'Buy / Sell',
    BUY: 'Buy',
    SELL: 'Sell',
    CONFIRM_TRADE: 'Confirm Trade',
    TREND_UP: 'Rising',
    TREND_DOWN: 'Falling',
    OBSERVED_ISSUE_REASON: 'Field issues reported: {issues}. Corrective action is mandatory.',
    OBSERVED_ISSUE_ACTION: 'Immediate leaf inspection & micro-nutrient application (Boron/Zinc).',
    OBSERVED_ISSUE_IMPACT: 'Symptoms like {issues} indicate root stress or nutrient lock.',
    OBSERVED_ISSUE_CONSEQUENCE: 'Significant Yield Reduction (30%+)',
    RAIN_LIKELY: 'Heavy Rain',
    NO_RAIN: 'No Rain',
    TEMP_RISK: 'Heat Wave',
    HUMIDITY_RISK: 'Low Humidity',
    WEATHER_NORMAL: 'Safe Day',
    WEATHER_ADVICE: 'Farmer Advice',
    SEVERITY_HIGH: 'High',
    SEVERITY_MEDIUM: 'Medium',
    SEVERITY_LOW: 'Low',
    RICE_BLAST_REASON: 'High risk of Rice Blast! Humidity (>85%) and cool nights are ideal for fungal spread.',
    RICE_BLAST_ACTION: 'Spray copper fungicide or bio-agent immediately. Ensure water drainage.',
    RICE_BLAST_IMPACT: 'Disease can spread across the entire field in days, causing 25%+ yield loss.',
    RICE_BLAST_CONSEQUENCE: 'Yield Loss (25-40%)',
    WHEAT_RUST_REASON: 'Wheat Rust alert! Humidity (>70%) and moderate temps are perfect for rust pustules.',
    WHEAT_RUST_ACTION: 'Apply propiconazole or organic alternatives. Monitor leaf surfaces for orange spots.',
    WHEAT_RUST_IMPACT: 'Rust stops grain filling, significantly reducing the final weight of your harvest.',
    WHEAT_RUST_CONSEQUENCE: 'Market Value Drop (20%)',
    FLOOD_ALERT_REASON: 'Prepare for flooding! Extreme rainfall forecast (>50mm).',
    FLOOD_ALERT_ACTION: 'Clear drainage channels immediately. Move harvest to higher ground.',
    FLOOD_ALERT_IMPACT: 'Flooding wipes out 80%+ of marginal farmers crops. Act within 12 hours.',
    FLOOD_ALERT_CONSEQUENCE: 'Total Yield Loss (80%+)',
    DROUGHT_WARNING_REASON: 'Severe drought risk! Extreme heat (>40°C) and no rain forecast.',
    DROUGHT_WARNING_ACTION: 'Protect crops — mulch now to retain moisture. Irrigate early morning.',
    DROUGHT_WARNING_IMPACT: 'Extreme weather events destroy most crops in bad years. Act now to save soil moisture.',
    DROUGHT_WARNING_CONSEQUENCE: 'Growth Stunted (40%)',
    PEST_SURGE_REASON: 'Pest surge alert! Humidity and temp are ideal for Aphids/Borers.',
    PEST_SURGE_ACTION: 'Apply neem spray for aphids immediately. Check undersides of leaves.',
    PEST_SURGE_IMPACT: 'Sudden surges wipe out 30% of yields. Eco-friendly fixes save money if used early.',
    PEST_SURGE_CONSEQUENCE: 'Partial Yield Loss (10-30%)',
    NUTRIENT_DEFICIENCY_REASON: 'Nutrient Deficiency detected! Symptoms: {issues}. Soil shows signs of depletion.',
    NUTRIENT_DEFICIENCY_ACTION: 'Apply Urea (20kg/ha) or Micro-nutrient spray immediately. Avoid chemical overuse.',
    NUTRIENT_DEFICIENCY_IMPACT: 'Nutrient imbalance reduces yield by 15-25% if not corrected early.',
    NUTRIENT_DEFICIENCY_CONSEQUENCE: 'Yield Drop (15-25%)',
    IRRIGATION_ALERT_REASON: 'Precise Irrigation Alert: Low soil moisture ({humidity}%) and high temp ({temp}°C).',
    IRRIGATION_ALERT_ACTION: 'Apply 2 inches of water today. Avoid middle-of-day watering to save 20% loss.',
    IRRIGATION_ALERT_IMPACT: 'Under-watering during this stage ({stage}) causes permanent wilting.',
    IRRIGATION_ALERT_CONSEQUENCE: 'Yield Quality Degradation',
    FINANCIAL_ALERT_REASON: 'Financial Risk: Potential debt trap! Institutional credit renewal due.',
    FINANCIAL_ALERT_ACTION: 'Visit local bank for KCC/PM Mudra renewal. Avoid 3% daily informal lenders.',
    FINANCIAL_ALERT_IMPACT: 'Informal debt interest can consume 50% of your harvest profit.',
    FINANCIAL_ALERT_CONSEQUENCE: 'Severe Financial Stress',
    POST_HARVEST_ALERT_REASON: 'Post-Harvest Opportunity: High market glut detected. Standard Mandi prices are falling.',
    POST_HARVEST_ALERT_ACTION: 'Group-sell with neighbors for transport savings. Dry crop to store for 30 days.',
    POST_HARVEST_ALERT_IMPACT: 'Selling during glut leads to 30% loss. Cold-chain or drying adds value.',
    POST_HARVEST_ALERT_CONSEQUENCE: 'Lost Profit Potential',
    DEFAULT_SAFE_REASON: 'Conditions are favorable for your crop stage.',
    DEFAULT_SAFE_ACTION: 'Continue standard maintenance and daily monitoring.'
  },
  hi: {
    APP_NAME: 'सामर्थ किसान',
    SUBTITLE: 'बेहतर फसल निर्णय',
    CROP_SETUP: 'होम',
    SIGNAL: 'संकेत',
    PAST_ALERTS: 'इतिहास',
    WEATHER_WATCH_TAB: 'मौसम',
    TRACKER_TAB: 'रिकॉर्ड',
    NOTIFICATIONS_TAB: 'अलर्ट',
    RISK_MONITOR_TAB: 'जोखिम',
    LOGBOOK_TAB: 'डायरी',
    SIMULATOR_TAB: 'सिमुलेशन',
    AI_CHAT_TAB: 'सहायक',
    AGRONOMIST_SCAN: 'कृषि वैज्ञानिक स्कैन',
    SELECT_CROP: '1. अपनी फसल चुनें',
    SELECT_SEASON: '2. सीजन चुनें',
    SOWING_DATE: '3. बुवाई की तारीख',
    SELECT_STAGE: '4. विकास का चरण',
    LOCATION: '5. जिला / स्थान',
    ISSUES: '6. कोई समस्या देखी?',
    CHECK_STATUS: 'फसल की स्थिति जांचें',
    LIVE_STATUS: 'लाइव स्थिति',
    UPDATE_DATA: 'डाटा अपडेट करें',
    SAFE_TITLE: 'सब ठीक है',
    WARNING_TITLE: 'ध्यान दें',
    ALERT_TITLE: 'महत्वपूर्ण कार्रवाई',
    WHAT_IF_TITLE: 'अगर मैं इसे नजरअंदाज करूँ?',
    RECOMMENDED_ACTION: 'सिफारिश की गई कार्रवाई',
    WHY_THIS_ALERT: 'यह अलर्ट क्यों?',
    WHY_EXPLANATION_TITLE: 'विवृत विवरण',
    AFFECTED_STAGE_LABEL: 'प्रभावित चरण',
    MATTERS_BECAUSE_LABEL: 'यह अभी क्यों महत्वपूर्ण है',
    URGENCY: 'तत्परता',
    WEATHER: 'मौसम की निगरानी',
    WEATHER_FORECAST: '5-दिवसीय पूर्वानुमान',
    HISTORY_TITLE: 'अलर्ट इतिहास',
    TRACKER_TITLE: 'फसल गतिविधि लॉग',
    NOTIFICATIONS_TITLE: 'हाल की सूचनाएं',
    TRACKER_PENDING: 'लंबित कार्य',
    TRACKER_LOGBOOK: 'गतिविधि इतिहास',
    LOGBOOK_TITLE: 'खेत की डायरी',
    LOGBOOK_DESC: 'आपकी खेती की गतिविधियों का विवरण',
    SIMULATOR_TITLE: 'सिनेरियो सिम्युलेटर',
    SIMULATOR_DESC: 'देखें मौसम के साथ अलर्ट कैसे बदलते हैं',
    AI_CHAT_TITLE: 'किसान सहायक AI',
    AI_CHAT_DESC: 'अपनी फसल के बारे में कुछ भी पूछें',
    SCAN_TITLE: 'डिजिटल कृषि विशेषज्ञ',
    SCAN_DESC: 'अपनी फसल या कीट की फोटो लें और लैब रिपोर्ट प्राप्त करें।',
    START_SCAN: 'नया स्कैन शुरू करें',
    SCANNING: 'लैब विश्लेषण चल रहा है...',
    SCAN_RESULT_TITLE: 'विशेषज्ञ लैब रिपोर्ट',
    DIAGNOSIS: 'रोग/कीट पहचान',
    ACTION_PLAN: 'कार्य योजना',
    PREVENTION: 'बचाव के उपाय',
    LISTEN_BTN: 'सलाह सुनें',
    STOP_LISTEN: 'बंद करें',
    CLEAR: 'साफ करें',
    NO_HISTORY: 'कोई रिकॉर्ड नहीं मिला।',
    ACTION_TAKEN: 'कार्रवाई की गई',
    ACTION_NOT_TAKEN: 'नहीं की गई',
    OFFLINE_BANNER: 'ऑफलाइन मोड – अंतिम उपलब्ध मार्गदर्शन दिखा रहा है।',
    CONFIDENCE: 'विश्वास स्तर',
    LOW_COST: 'किफायती समाधान',
    FEEDBACK_BTN: 'पूरा किया',
    FEEDBACK_DONE: 'कार्रवाई दर्ज की गई ✓',
    STAGE_SUGGESTION: 'अनुमानित चरण:',
    NEXT_STAGE: 'अगला चरण',
    DAYS_REMAINING: 'दिन बचे हैं',
    CROP_TIMELINE: 'फसल की प्रगति',
    IGNORE_RISK_HOURS: '{h} घंटों के भीतर कार्रवाई की आवश्यकता',
    IGNORE_RISK_DAYS: '{d} दिनों के भीतर कार्रवाई की आवश्यकता',
    MARKET_ACCESS: 'बाजार संपर्क',
    MARKET_PRICE: 'मंडी भाव',
    BUY_SELL: 'खरीदें / बेचें',
    BUY: 'खरीदें',
    SELL: 'बेचें',
    CONFIRM_TRADE: 'सौदा पक्का करें',
    TREND_UP: 'बढ़ रहा है',
    TREND_DOWN: 'गिर रहा है',
    OBSERVED_ISSUE_REASON: 'रिपोर्ट की गई समस्याएं: {issues}। सुधारात्मक कार्रवाई अनिवार्य है।',
    OBSERVED_ISSUE_ACTION: 'पत्तियों का निरीक्षण और सूक्ष्म पोषक तत्वों का छिड़काव करें।',
    OBSERVED_ISSUE_IMPACT: '{issues} पोषक तत्वों की कमी का संकेत देते हैं।',
    OBSERVED_ISSUE_CONSEQUENCE: 'उपज में भारी कमी (30%+)',
    RAIN_LIKELY: 'भारी बारिश',
    NO_RAIN: 'कोई बारिश नहीं',
    TEMP_RISK: 'लू का खतरा',
    HUMIDITY_RISK: 'कम नमी',
    WEATHER_NORMAL: 'सुरक्षित दिन',
    WEATHER_ADVICE: 'किसान सलाह',
    SEVERITY_HIGH: 'उच्च',
    SEVERITY_MEDIUM: 'मध्यम',
    SEVERITY_LOW: 'कम',
    RICE_BLAST_REASON: 'चावल में ब्लास्ट का खतरा! अधिक नमी और ठंडी रातें संक्रमण के लिए अनुकूल हैं।',
    RICE_BLAST_ACTION: 'कॉपर फंगीसाइड का छिड़काव करें। जल निकासी सुनिश्चित करें।',
    RICE_BLAST_IMPACT: 'चावल में ब्लास्ट रोग कुछ ही दिनों में पूरे खेत में फैल सकता है, जिससे उपज में 25% से अधिक की कमी हो सकती है।',
    RICE_BLAST_CONSEQUENCE: 'उपज हानि (25-40%)',
    WHEAT_RUST_REASON: 'गेहूं में रस्ट अलर्ट! नमी और मध्यम तापमान संक्रमण को बढ़ा सकते हैं।',
    WHEAT_RUST_ACTION: 'प्रोपिकोनाज़ोल का छिड़काव करें। पत्तों पर नारंगी धब्बों की जांच करें।',
    WHEAT_RUST_IMPACT: 'रस्ट अनाज के भराव को रोकता है, जिससे आपकी फसल का अंतिम वजन काफी कम हो जाता है।',
    WHEAT_RUST_CONSEQUENCE: 'बाजार मूल्य में गिरावट (20%)',
    FLOOD_ALERT_REASON: 'बाढ़ के लिए तैयार रहें! अत्यधिक बारिश का अनुमान।',
    FLOOD_ALERT_ACTION: 'जल निकासी नालियों को साफ करें। कटी हुई फसल को तुरंत ऊंचे स्थान पर ले जाएं।',
    FLOOD_ALERT_IMPACT: 'बाढ़ से सीमांत किसानों की 80% से अधिक फसल नष्ट हो जाती है। 12 घंटे के भीतर कार्रवाई करें।',
    FLOOD_ALERT_CONSEQUENCE: 'कुल उपज हानि (80%+)',
    DROUGHT_WARNING_REASON: 'सूखे का गंभीर खतरा! अत्यधिक गर्मी और कोई बारिश नहीं।',
    DROUGHT_WARNING_ACTION: 'फसल बचाएं — नमी बनाए रखने के लिए अभी मल्चिंग करें।',
    DROUGHT_WARNING_IMPACT: 'अत्यधिक गर्मी और सूखे से अधिकांश फसलें नष्ट हो सकती हैं। मिट्टी की नमी बचाने के लिए अभी मल्चिंग करें।',
    DROUGHT_WARNING_CONSEQUENCE: 'विकास अवरुद्ध (40%)',
    PEST_SURGE_REASON: 'कीटों का हमला! नमी और तापमान कीटों के लिए अनुकूल हैं।',
    PEST_SURGE_ACTION: 'नीम के तेल का छिड़काव करें। पत्तों के नीचे जांच करें।',
    PEST_SURGE_IMPACT: 'कीटों का हमला अचानक 30% तक उपज को खत्म कर सकता है। समय पर उपचार जरूरी है।',
    PEST_SURGE_CONSEQUENCE: 'आंशिक उपज हानि (10-30%)',
    NUTRIENT_DEFICIENCY_REASON: 'पोषक तत्वों की कमी! मिट्टी में कमी के संकेत हैं।',
    NUTRIENT_DEFICIENCY_ACTION: 'तुरंत यूरिया (20kg/ha) या सूक्ष्म पोषक स्प्रे का उपयोग करें।',
    NUTRIENT_DEFICIENCY_IMPACT: 'पोषक तत्वों का असंतुलन सही न किए जाने पर उपज में 15-25% की कमी लाता है।',
    NUTRIENT_DEFICIENCY_CONSEQUENCE: 'उपज में गिरावट (15-25%)',
    IRRIGATION_ALERT_REASON: 'सिंचाई अलर्ट: मिट्टी की कम नमी और उच्च तापमान।',
    IRRIGATION_ALERT_ACTION: 'आज ही पानी दें। सुबह या शाम को पानी देकर 20% बचत करें।',
    IRRIGATION_ALERT_IMPACT: 'इस चरण ({stage}) के दौरान कम सिंचाई से फसल मुरझा सकती है।',
    IRRIGATION_ALERT_CONSEQUENCE: 'उपज की गुणवत्ता में गिरावट',
    FINANCIAL_ALERT_REASON: 'वित्तीय जोखिम: कर्ज का जाल! संस्थागत ऋण नवीनीकरण का समय।',
    FINANCIAL_ALERT_ACTION: 'KCC/PM मुद्रा नवीनीकरण के लिए बैंक जाएं। अनौपचारिक साहूकारों से बचें।',
    FINANCIAL_ALERT_IMPACT: 'साहूकारों का ब्याज आपके फसल लाभ का 50% खा सकता है।',
    FINANCIAL_ALERT_CONSEQUENCE: 'गंभीर वित्तीय तनाव',
    POST_HARVEST_ALERT_REASON: 'कटाई के बाद का अवसर: मंडी में भारी आवक से कीमतें गिर रही हैं।',
    POST_HARVEST_ALERT_ACTION: 'पड़ोसियों के साथ मिलकर फसल बेचें। फसल सुखाकर भंडारण करें।',
    POST_HARVEST_ALERT_IMPACT: 'बाजार में मंदी के दौरान बेचने से 30% तक की हानि हो सकती है। फसल को सुखाकर भंडारण करें।',
    POST_HARVEST_ALERT_CONSEQUENCE: 'लाभ की संभावना कम होना',
    DEFAULT_SAFE_REASON: 'परिस्थितियाँ आपकी फसल के चरण के अनुकूल हैं।',
    DEFAULT_SAFE_ACTION: 'नियमित रखरखाव जारी रखें।'
  },
  te: {
    APP_NAME: 'సమర్థ్ కిసాన్',
    SUBTITLE: 'తెలివైన పంట నిర్ణయాలు',
    CROP_SETUP: 'హోమ్',
    SIGNAL: 'సిగ్నల్',
    PAST_ALERTS: 'చరిత్ర',
    WEATHER_WATCH_TAB: 'వాతావరణం',
    TRACKER_TAB: 'రికార్డ్స్',
    NOTIFICATIONS_TAB: 'అలర్ట్స్',
    RISK_MONITOR_TAB: 'ముప్పు',
    LOGBOOK_TAB: 'డైరీ',
    SIMULATOR_TAB: 'సిమ్యులేషన్',
    AI_CHAT_TAB: 'సహాయక్',
    AGRONOMIST_SCAN: 'వ్యవసాయ నిపుణుల స్కాన్',
    SELECT_CROP: '1. మీ పంటను ఎంచుకోండి',
    SELECT_SEASON: '2. సీజన్ ఎంచుకోండి',
    SOWING_DATE: '3. విత్తిన తేదీ',
    SELECT_STAGE: '4. ప్రస్తుత దశ',
    LOCATION: '5. జిల్లా / ప్రాంతం',
    ISSUES: '6. పొలంలో సమస్యలు ఉన్నాయా?',
    CHECK_STATUS: 'స్థితిని తనిఖీ చేయండి',
    LIVE_STATUS: 'లైవ్ స్థితి',
    UPDATE_DATA: 'డేటా అప్‌డేట్',
    SAFE_TITLE: 'అంతా బాగుంది',
    WARNING_TITLE: 'శ్రద్ధ వహించండి',
    ALERT_TITLE: 'కీలక చర్య',
    WHAT_IF_TITLE: 'నేను దీన్ని పట్టించుకోకపోతే?',
    RECOMMENDED_ACTION: 'సిఫార్సు చేసిన చర్య',
    WHY_THIS_ALERT: 'ఈ హెచ్చరిక ఎందుకు?',
    WHY_EXPLANATION_TITLE: 'వివరణాత్మక వివరణ',
    AFFECTED_STAGE_LABEL: 'ప్రభావిత దశ',
    MATTERS_BECAUSE_LABEL: 'ఇది ఇప్పుడు ఎందుకు ముఖ్యం',
    URGENCY: 'అవసరం',
    WEATHER: 'వాతావరణ పరిశీలన',
    WEATHER_FORECAST: '5 రోజుల వాతావరణం',
    HISTORY_TITLE: 'హెచ్చరిక చరిత్ర',
    TRACKER_TITLE: 'వ్యవసాయ కార్యకలాపాల లాగ్',
    NOTIFICATIONS_TITLE: 'ఇటీవలి నోటిఫికేషన్‌లు',
    TRACKER_PENDING: 'పెండింగ్ పనులు',
    TRACKER_LOGBOOK: 'కార్యకలాపాల చరిత్ర',
    LOGBOOK_TITLE: 'ఫామ్ లాగ్‌బుక్',
    LOGBOOK_DESC: 'మీ వ్యవసాయ కార్యకలాపాల డైరీ',
    SIMULATOR_TITLE: 'సిమ్యులేటర్',
    SIMULATOR_DESC: 'వాతావరణంతో అలర్ట్‌లు ఎలా మారుతాయో చూడండి',
    AI_CHAT_TITLE: 'కిసాన్ సహాయక్ AI',
    AI_CHAT_DESC: 'మీ పంట గురించి ఏదైనా అడగండి',
    SCAN_TITLE: 'డిజిటల్ వ్యవసాయ నిపుణుడు',
    SCAN_DESC: 'మీ పంట లేదా పురుగు ఫోటో తీయండి, ల్యాబ్ రిపోర్ట్ పొందండి.',
    START_SCAN: 'కొత్త స్కాన్ ప్రారంభించండి',
    SCANNING: 'ల్యాబ్ విశ్లేషణ జరుగుతోంది...',
    SCAN_RESULT_TITLE: 'వ్యవసాయ నిపుణుల ల్యాబ్ రిపోర్ట్',
    DIAGNOSIS: 'రోగ నిర్ధారణ',
    ACTION_PLAN: 'చర్య ప్రణాళిక',
    PREVENTION: 'నివారణ చర్యలు',
    LISTEN_BTN: 'సలహా వినండి',
    STOP_LISTEN: 'ఆపండి',
    CLEAR: 'క్లియర్ చేయండి',
    NO_HISTORY: 'రికార్డులు లేవు.',
    ACTION_TAKEN: 'పూర్తయింది',
    ACTION_NOT_TAKEN: 'కాలేదు',
    OFFLINE_BANNER: 'ఆఫ్లైన్ మోడ్ – చివరి అందుబాటులో ఉన్న మార్గదర్శకాన్ని చూపిస్తోంది.',
    CONFIDENCE: 'నమ్మకం స్థాయి',
    LOW_COST: 'తక్కువ ఖర్చు',
    FEEDBACK_BTN: 'పూర్తి చేసాను',
    FEEDBACK_DONE: 'చర్య నమోదు చేయబడింది ✓',
    STAGE_SUGGESTION: 'అంచనా దశ:',
    NEXT_STAGE: 'తదుపరి దశ',
    DAYS_REMAINING: 'రోజులు మిగిలి ఉన్నాయి',
    CROP_TIMELINE: 'పంట పురోగతి',
    IGNORE_RISK_HOURS: '{h} గంటల్లో చర్య తీసుకోవాలి',
    IGNORE_RISK_DAYS: '{d} రోజుల్లో చర్య తీసుకోవాలి',
    MARKET_ACCESS: 'మార్కెట్ కనెక్ట్',
    MARKET_PRICE: 'మార్కెట్ ధర',
    BUY_SELL: 'కొనుగోలు / విక్రయం',
    BUY: 'కొనుగోలు',
    SELL: 'విక్రయం',
    CONFIRM_TRADE: 'ట్రేడ్ ధృవీకరించు',
    TREND_UP: 'పెరుగుతోంది',
    TREND_DOWN: 'తగ్గుతోంది',
    OBSERVED_ISSUE_REASON: 'సమస్యలు గుర్తించబడ్డాయి: {issues}. తక్షణ చర్య అవసరం.',
    OBSERVED_ISSUE_ACTION: 'ఆకులను పరిశీలించి సూక్ష్మ పోషకాలను వాడండి.',
    OBSERVED_ISSUE_IMPACT: '{issues} పోషకాల లోపాన్ని సూచిస్తున్నాయి.',
    OBSERVED_ISSUE_CONSEQUENCE: 'దిగుబడి భారీగా తగ్గే అవకాశం (30%+)',
    RAIN_LIKELY: 'భారీ వర్షం',
    NO_RAIN: 'వర్షం లేదు',
    TEMP_RISK: 'వడగాల్పులు',
    HUMIDITY_RISK: 'తక్కువ తేమ',
    WEATHER_NORMAL: 'సాధారణం',
    WEATHER_ADVICE: 'రైతు సలహా',
    SEVERITY_HIGH: 'ఎక్కువ',
    SEVERITY_MEDIUM: 'మధ్యస్థం',
    SEVERITY_LOW: 'తక్కువ',
    RICE_BLAST_REASON: 'వరిలో బ్లాస్ట్ ముప్పు! అధిక తేమ మరియు చల్లని రాత్రులు శిలీంధ్ర వ్యాప్తికి అనుకూలం.',
    RICE_BLAST_ACTION: 'కాపర్ ఫంగీసైడ్ వాడండి. నీటి పారుదల బాగుండేలా చూడండి.',
    RICE_BLAST_IMPACT: 'వరి బ్లాస్ట్ వ్యాధి పొలమంతా వేగంగా విస్తరించి 25% పైగా దిగుబడిని తగ్గిస్తుంది.',
    RICE_BLAST_CONSEQUENCE: 'దిగుబడి నష్టం (25-40%)',
    WHEAT_RUST_REASON: 'గోధుమలో రస్ట్ హెచ్చరిక! తేమ మరియు మధ్యస్థ ఉష్ణోగ్రతలు అనుకూలం.',
    WHEAT_RUST_ACTION: 'ప్రొపికోనజోల్ వాడండి. ఆకులపై నారింజ మచ్చలను గమనిండి.',
    WHEAT_RUST_IMPACT: 'రస్ట్ వల్ల గింజ సరిగ్గా రాదు, దీనివల్ల దిగుబడి బరువు తగ్గుతుంది.',
    WHEAT_RUST_CONSEQUENCE: 'మార్కెట్ ధర తగ్గింపు (20%)',
    FLOOD_ALERT_REASON: 'వరద హెచ్చరిక! అత్యంత భారీ వర్ష సూచన.',
    FLOOD_ALERT_ACTION: 'నీటి పారుదల కాలువలను శుభ్రం చేయండి. పంటను సురక్షిత ప్రాంతానికి తరలించండి.',
    FLOOD_ALERT_IMPACT: 'వరదల వల్ల 80% పైగా పంట నష్టపోయే అవకాశం ఉంది. 12 గంటల్లో స్పందించండి.',
    FLOOD_ALERT_CONSEQUENCE: 'పూర్తి దిగుబడి నష్టం (80%+)',
    DROUGHT_WARNING_REASON: 'తీవ్ర కరువు ముప్పు! అధిక ఉష్ణోగ్రతలు మరియు వర్షం లేని సూచన.',
    DROUGHT_WARNING_ACTION: 'తేమను కాపాడటానికి మల్చింగ్ చేయండి. తెల్లవారుజామునే నీరు పెట్టండి.',
    DROUGHT_WARNING_IMPACT: 'తీవ్రమైన ఎండలు పంటను నాశనం చేస్తాయి. తేమను కాపాడటానికి చర్యలు తీసుకోండి.',
    DROUGHT_WARNING_CONSEQUENCE: 'పెరుగుదల కుంటుపడుతుంది (40%)',
    PEST_SURGE_REASON: 'కీటకాల వ్యాప్తి! తేమ మరియు ఉష్ణోగ్రతలు కీటకాలకు అనుకూలం.',
    PEST_SURGE_ACTION: 'వేప నూనె వాడండి. ఆకుల అడుగు భాగాన్ని పరిశీలించండి.',
    PEST_SURGE_IMPACT: 'కీటకాల వ్యాప్తి వల్ల 30% దిగుబడి తగ్గే అవకాశం ఉంది.',
    PEST_SURGE_CONSEQUENCE: 'పాక్షిక దిగుబడి నష్టం (10-30%)',
    NUTRIENT_DEFICIENCY_REASON: 'పోషకాల లోపం! నేల సారం తగ్గుతోంది.',
    NUTRIENT_DEFICIENCY_ACTION: 'వెంటనే యూరియా లేదా మైక్రో-న్యూట్రియెంట్ స్ప్రే వాడండి.',
    NUTRIENT_DEFICIENCY_IMPACT: 'పోషకాల లోపం వల్ల దిగుబడి 15-25% వరకు తగ్గుతుంది.',
    NUTRIENT_DEFICIENCY_CONSEQUENCE: 'దిగుబడి తగ్గుదల (15-25%)',
    IRRIGATION_ALERT_REASON: 'నీటి తడుల హెచ్చరిక: నేలలో తేమ తక్కువగా ఉంది.',
    IRRIGATION_ALERT_ACTION: 'ఈరోజే నీరు పెట్టండి. ఉదయం లేదా సాయంత్రం నీరు పెట్టి 20% నీటిని ఆదా చేయండి.',
    IRRIGATION_ALERT_IMPACT: 'ఈ దశలో ({stage}) నీరు సరిగ్గా పెట్టకపోతే పంట వాడిపోతుంది.',
    IRRIGATION_ALERT_CONSEQUENCE: 'దిగుబడి నాణ్యత తగ్గుదల',
    FINANCIAL_ALERT_REASON: 'ఆర్థిక ముప్పు: అప్పుల ఊబి! బ్యాంకు రుణం పునరుద్ధరణ సమయం.',
    FINANCIAL_ALERT_ACTION: 'KCC/PM ముద్ర పునరుద్ధరణ కోసం బ్యాంకును సంప్రదించండి. వడ్డీ వ్యాపారుల వద్ద అప్పు తీసుకోవద్దు.',
    FINANCIAL_ALERT_IMPACT: 'అప్పుల వడ్డీ మీ లాభాన్ని హరిస్తుంది. తక్కువ వడ్డీ రుణాలకే ప్రాధాన్యత ఇవ్వండి.',
    FINANCIAL_ALERT_CONSEQUENCE: 'తీవ్ర ఆర్థిక ఒత్తిడి',
    POST_HARVEST_ALERT_REASON: 'కోత అనంతర అవకాశం: మార్కెట్లో పంట నిల్వలు పెరిగి ధరలు తగ్గుతున్నాయి.',
    POST_HARVEST_ALERT_ACTION: 'పక్క రైతులతో కలిసి పంటను రవాణా చేయండి. పంటను ఎండబెట్టి నిల్వ చేయండి.',
    POST_HARVEST_ALERT_IMPACT: 'మార్కెట్ రద్దీ సమయంలో అమ్మితే 30% నష్టం వచ్చే అవకాశం ఉంది. పంటను ఎండబెట్టి నిల్వ చేయండి.',
    POST_HARVEST_ALERT_CONSEQUENCE: 'లాభం తగ్గే అవకాశం',
    DEFAULT_SAFE_REASON: 'పరిస్థితులు పంటకు అనుకూలంగా ఉన్నాయి.',
    DEFAULT_SAFE_ACTION: 'సాధారణ పర్యవేక్షణ కొనసాగించండి.'
  }
};

export const RULES: DecisionRule[] = [
  {
    crop: CropType.RICE,
    stage: CropStage.FLOWERING,
    condition: (w) => w.humidity > 85 && w.temp < 25,
    ruleKey: 'RICE_BLAST',
    isLowCost: true
  },
  {
    crop: CropType.WHEAT,
    stage: CropStage.GROWTH,
    condition: (w) => w.humidity > 70 && w.temp >= 15 && w.temp <= 20,
    ruleKey: 'WHEAT_RUST',
    isLowCost: true
  },
  {
    crop: CropType.RICE,
    stage: CropStage.GROWTH,
    condition: (w) => w.rainForecast > 50,
    ruleKey: 'FLOOD_ALERT',
    isLowCost: false
  },
  {
    crop: CropType.WHEAT,
    stage: CropStage.GROWTH,
    condition: (w) => w.rainForecast > 50,
    ruleKey: 'FLOOD_ALERT',
    isLowCost: false
  },
  {
    crop: CropType.COTTON,
    stage: CropStage.GROWTH,
    condition: (w) => w.temp > 40 && w.rainForecast < 2,
    ruleKey: 'DROUGHT_WARNING',
    isLowCost: true
  },
  {
    crop: CropType.MAIZE,
    stage: CropStage.GROWTH,
    condition: (w) => w.humidity > 80 && w.temp > 20 && w.temp < 30,
    ruleKey: 'PEST_SURGE',
    isLowCost: true
  },
  {
    crop: CropType.RICE,
    stage: CropStage.GROWTH,
    condition: (_, issues) => issues.includes('Yellowing leaves') || issues.includes('Stunted growth'),
    ruleKey: 'NUTRIENT_DEFICIENCY',
    isLowCost: true
  },
  {
    crop: CropType.WHEAT,
    stage: CropStage.GROWTH,
    condition: (_, issues) => issues.includes('Yellowing leaves') || issues.includes('Stunted growth'),
    ruleKey: 'NUTRIENT_DEFICIENCY',
    isLowCost: true
  },
  {
    crop: CropType.COTTON,
    stage: CropStage.GROWTH,
    condition: (w) => w.temp > 32 && w.rainForecast < 5,
    ruleKey: 'IRRIGATION_ALERT',
    isLowCost: true
  },
  {
    crop: CropType.MAIZE,
    stage: CropStage.GROWTH,
    condition: (w) => w.temp > 32 && w.rainForecast < 5,
    ruleKey: 'IRRIGATION_ALERT',
    isLowCost: true
  },
  {
    crop: CropType.RICE,
    stage: CropStage.HARVEST,
    condition: (w) => w.temp > 35,
    ruleKey: 'POST_HARVEST_ALERT',
    isLowCost: true
  },
  {
    crop: CropType.WHEAT,
    stage: CropStage.HARVEST,
    condition: (w) => w.rainForecast > 10,
    ruleKey: 'POST_HARVEST_ALERT',
    isLowCost: true
  }
];
